title: "Subhas Galam"
logo: "/assets/img/headshot_circle.png"
remote_theme: "mmistakes/minimal-mistakes"
show_downloads: false
description: "Data Scientist | ML Engineer | DevOps | Cloud"

# Navigation
header_pages:
  - index.md
  - about.md
  - projects.md
  - blog.md

# Sidebar Settings
sidebar:
  - image: "/assets/img/headshot_circle.png"
    image_circular: true
    tagline: "Data Science | ML | NLP | DevOps"
    social_links:
      - name: "GitHub"
        url: "https://github.com/subbugalam47"
      - name: "Leetcode"
        url: "https://leetcode.com/u/subbu-galam_69/"
      - name: "LinkedIn"
        url: "https://www.linkedin.com/in/subbu-galam"
      - name: "HackerRank"
        url: "https://www.hackerrank.com/profile/subbugalam69"

# Plugins (GitHub auto-runs Jekyll)
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-minifier
